version: '3.8'
services:
  api:
    build: api
    environment:
      - POSTCODES_SERVICE_URL=http://postcodes:8001
    ports:
      - "8000:8000"
    volumes:
      - ./api/django_api/db:/app/django_api/db
  postcodes:
    build: postcodes
